### ISSUE TITLE
"Experience" section, start on new page.

### ISSUE THREAD

**Issue by kyrolloszakaria** [mattyHerzig/mattys_resume#1]
"Experience" section, start on new pages if there isn't enough space for the whole section.

![image](https://github.com/mattyHerzig/mattys_resume/assets/76782214/ad6fb250-4623-446a-9135-b1999d033b51)

**Comment by mattyHerzig** [comment]
Hm, I see. One hacky workaround is too add `\goodbreak\ ` (with a space after the second backslash) after the last project that the first page has space for. I've attached a preview here. Does this work you, is the behavior you intended? (Although I should emphasize that this template is meant to be used with one page, as is typically recommended, although I understand the possibility of needing to go beyond that)
![image](https://github.com/mattyHerzig/mattys_resume/assets/112666119/f12beac6-1c5d-4498-94da-7f865bc8ff92)

**Comment by kyrolloszakaria** [comment]
Yes, it worked! Thank you so much.
Also, if `\goodbreak\ ` did not work for anyone, he can try to end the resumeItemsList, put a page break, and then strat a new list.
![image](https://github.com/mattyHerzig/mattys_resume/assets/76782214/df229342-a39f-458c-a7a9-d99734fc6da4)
