### ISSUE TITLE
standardize the text size for all the dates

### ISSUE THREAD

**Issue by TheColorDarkBlue** [mattyHerzig/mattys_resume#2]
right now the text size is inconsistent across the document

**Comment by mattyHerzig** [comment]
Thanks for the feedback! I've fixed the inconsistent text size for dates. Here is a picture of the change:
![image](https://github.com/user-attachments/assets/043c3b6b-993d-43a9-8d09-1e35c0f72566)
Once Overleaf approves the new submission, I can update the link on this repo. For now, if you want the sizing fixed, you can consider the changes to the `.tex` file. Let me know if this doesn't work for you :)
